---
- name: Install nginx on deb-based distributive
  apt:
    name: "nginx"
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' or
        ansible_distribution == 'Debian'
  tags:
    - nginx_install_deb_based_distr

- name: Install nginx on rpm-based distributive
  yum:
    name: "nginx"
    state: present
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux' or
        (ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2')
  tags:
    - nginx_install_rpm_based_disrt

- name: Add support for ssl connections
  include_role:
    name: ssl
  when:
    -  ssl_connect|bool == true
  tags:
    - install_ssl_support