---
- name: Install EPEL repo on rpm-based distributive
  yum:
    name:  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install EPEL gpg-key on rpm-based distributive
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  tags:
    - epel_gpg_key_install

- name: Enable EPEL repo
  ini_file:
    dest: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: '1'

- name: Install basic packages on rpm-based distributive
  yum:
    name:
      - htop
      - atop
      - iftop
      - vim-enhanced
      - wget
      - curl
      - net-snmp
    state: present
  tags:
    - base_install_basic_packages
